# BLAS ASSIGNMENT

Use the cell below for all your imports.

In [1]:
import numpy as np
from scipy.linalg.blas import dgemv, ddot, dnrm2

Create a matrix and a vector using NumPy.Their dtype should be double.

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
x = np.array([1, 2, 3], dtype=np.double)

*Use* BLAS functions to perform matrix-vector multiplication

1.   Élément de liste
2.   Élément de liste



In [3]:
y = np.zeros_like(x)
alpha = 1.0
beta = 0.0
dgemv(alpha, A, x, beta, y)
print(y)

[0. 0. 0.]


In [4]:
import numpy as np
from scipy.linalg import blas
#*Use* BLAS functions to perform matrix-vector multiplication


c=blas.dgemv(alpha, A, x, beta, y)

print(c)





[14. 32. 50.]


Create two new vectors and calculate their dot product using BLAS functions.

In [5]:
a = np.array([1, 2, 3], dtype=np.double)
b = np.array([4, 5, 6], dtype=np.double)
result = ddot(a, b)
print(result)

32.0


In [6]:
blas.ddot(a,b)

32.0

Compute the L2 norm (Euclidean distance) of a vector using BLAS functions

In [7]:
a = np.array([1, 2, 3], dtype=np.double)
norm = dnrm2(a)
print(norm)

3.7416573867739413


In [8]:
blas.dnrm2(a)

3.7416573867739413

Create a 5x5 symmetric matrix and calculate its eigenvalues and eigenvectors using BLAS functions

In [9]:
import numpy as np
from scipy.linalg import eigh

# Define the 5x5 symmetric matrix
A = np.array([[1, 2, 3, 4, 5], [2, 6, 7, 8, 9], [3, 7, 10, 11, 12], [4, 8, 11, 13, 14], [5, 9, 12, 14, 15]], dtype=np.double)
A = 0.5 * (A + A.T) # make sure A is symmetric

# Define the input vector
x = np.array([1, 2, 3, 4, 5], dtype=np.double)

# Calculate the matrix-vector product using BLAS functions
y = np.dot(A, x)

# Calculate the eigenvalues and eigenvectors using the eigh function
w, v = eigh(A)

# Print the results
print("Matrix A:\n", A)
print("Vector x:\n", x)
print("Matrix-vector product y:\n", y)
print("Eigenvalues:", w)
print("Eigenvectors:\n", v)


Matrix A:
 [[ 1.  2.  3.  4.  5.]
 [ 2.  6.  7.  8.  9.]
 [ 3.  7. 10. 11. 12.]
 [ 4.  8. 11. 13. 14.]
 [ 5.  9. 12. 14. 15.]]
Vector x:
 [1. 2. 3. 4. 5.]
Matrix-vector product y:
 [ 55. 112. 151. 175. 190.]
Eigenvalues: [-1.06976654  0.17107866  0.66327097  1.12044198 44.11497493]
Eigenvectors:
 [[ 0.74040618  0.29272354 -0.2622205   0.51923398 -0.16657759]
 [ 0.25877317 -0.01176247 -0.5205591  -0.73629348 -0.34610435]
 [ 0.20831227  0.32514414  0.75652334 -0.24779322 -0.4660024 ]
 [ 0.05805977 -0.80337432  0.07392338  0.23445474 -0.53924491]
 [-0.58143804  0.40378901 -0.28716962  0.26813704 -0.58695859]]


In [10]:
import numpy as np
from scipy.linalg import eigh

# Define the symmetric matrix
A = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]], dtype=np.double)

# Compute the eigenvalues and eigenvectors using eigh
w, v = eigh(A)

# Print the results
print("Eigenvalues:", w)
print("Eigenvectors:\n", v)


Eigenvalues: [-0.51572947  0.17091519 11.34481428]
Eigenvectors:
 [[ 0.73697623  0.59100905 -0.32798528]
 [ 0.32798528 -0.73697623 -0.59100905]
 [-0.59100905  0.32798528 -0.73697623]]


In [12]:
import scipy
print(scipy.__version__)


1.10.1


In [13]:
!pip install --upgrade scipy


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Given the following matrix `A` and vector `v`: 

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.double)
b = np.array([1, 2, 3], dtype=np.double)

Solve the system `Ax = b` using the LU decomposition method and BLAS functions

> Bloc en retrait



In [16]:
import scipy.linalg.lapack as lapack
print(lapack.get_lapack_funcs(('getrf',), (np.array([], dtype=np.double),))[0])

<fortran object>


In [21]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve

# Define the matrix A and vector b
# Define the matrix A and vector b
A = np.array([[1, 2, 3], [2, 5, 1], [4, 7, 2]], dtype=np.double)
b = np.array([4, 5, 6], dtype=np.double)


# Compute the LU decomposition of A using the lu_factor function
lu, piv = lu_factor(A)

# Solve the system Ax = b using the lu_solve function
x = lu_solve((lu, piv), b)

# Print the results
print("Matrix A:\n", A)
print("Vector b:\n", b)
print("Solution x:\n", x)

print("Solution x:\n", x)


Matrix A:
 [[1. 2. 3.]
 [2. 5. 1.]
 [4. 7. 2.]]
Vector b:
 [4. 5. 6.]
Solution x:
 [-1.26666667  1.33333333  0.86666667]
Solution x:
 [-1.26666667  1.33333333  0.86666667]
